// <auto-generated />
namespace PosLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PaymentColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaymentColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202108170403090_PaymentColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
